version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - db
    working_dir: /var/www/laravel
    networks:
      - laravel_net
    command: php-fpm

  db:
    image: mariadb:10.6  # Versión LTS estable
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laravel
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"   # Exponemos en 3307 para no chocar con MariaDB local
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

volumes:
  dbdata:

networks:
  laravel_net:
    driver: bridge
